### ISSUE TITLE
Looking Good

### ISSUE THREAD

**Issue by dbushy727** [mshaf/SMBD#1]
Looks good man!

![](https://media.giphy.com/media/ohMtDzrhrWgnK/giphy.gif)

 Functionality is there.. Now time for V2.
## Front End
- Install Bootstrap http://www.getbootstrap.com
  - Instead of floating the image, use the grid system to divide up the page into two halves.
    - Left side should be the image
    - Right side should be a "panel" with the movie data. 
  - Use bootstrap classes for inputs and buttons
  - Add Labels for the movie info in the panel
    - Examples: 
      - Title: Casino
      - Actors: Robert DeNiro, Sharon Stone, Joe Pesci
## Back End
- Add some more movie data so the app looks complete
- Search when hitting the enter key
- Add Rotten Tomatoes info

**Comment by mshaf** [comment]
I think I got everything done, plus added a little CLE joke to the results
